<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>FSH.Modules.Organization</RootNamespace>
        <AssemblyName>FSH.Modules.Organization</AssemblyName>
        <PackageId>FullStackHero.Modules.Organization</PackageId>
        <NoWarn>$(NoWarn);CA1031;CA1812;CA1859;S3267;S1144</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\Persistence\Persistence.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\Web\Web.csproj" />
        <ProjectReference Include="..\Modules.Organization.Contracts\Modules.Organization.Contracts.csproj" />
    </ItemGroup>

</Project>
